services:
  db:
    image: postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - ./src/lib/server/db/migrations:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
